### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by tbirdso** [slicersalt/ITKShape#19]
`itk-shape` has an entry at [https://pypi.org/project/itk-shape/](https://pypi.org/project/itk-shape/) but attempting to install with `pip install itk-shape` fails:
> \>pip install itk-shape==0.1.0
ERROR: Could not find a version that satisfies the requirement itk-shape==0.1.0 (from versions: none)
ERROR: No matching distribution found for itk-shape==0.1.0

@thewtex Could you clarify what other steps we need to take to publish a new package to Pypi? Are we missing credentials for this repo?

Note that this isn't a blocking issue, we can build the cxx project against a local ITK build, but it would be useful to have a Python package we can freely install as a testing dependency as we move forward on the HASI Python pipeline.

**Comment by thewtex** [comment]
@tbirdso to upload a new revision:

1) Create a PR that bumps the versions of ITK in the CI configuration (it should now be `v5.2.0` for the C++ builds and `v5.2.0.post2` for the Python builds. The PR should also update the itk-shape version in *setup.py* and the required `itk` version in *setup.py*.
2) After merged, tag the repository with the updated version, e.g. `v0.2.0`.
3) The CI does the rest :-)
