### ISSUE TITLE
CMake errors linking ITK modules

### ISSUE THREAD

**Issue by tbirdso** [slicersalt/ITKShape#2]
## Overview
Initial files in [PR 1](https://github.com/slicersalt/ITKMesh3DProcrustesAlignFilter/pulls/1) fail to build with CMake.

## Description
[PR 1](https://github.com/slicersalt/ITKMesh3DProcrustesAlignFilter/pulls/1) adds an ITK external module created with `cookiecutter` from the ITK external module template, along with header, template, and wrapping files for `Mesh3DProcrustesAlignFilter`. `itk-module.cmake` is updated with ITK module dependencies. Attempting to build with CMake yields an error indicating that ITK modules are not linked successfully to allow the headers to be built.

## Expected behavior
External module builds without error.

## Observed behavior
[CDash failures](https://open.cdash.org/build/7080389):

> include/itkMesh3DProcrustesAlignFilter.h:5:10: fatal error: itkAffineTransform.h: No such file or directory

Contents of CMakeError.log:
> Performing Test ITK_UNDEFINED_SYMBOLS_ALLOWED failed with the following output:

(no output follows)

**Comment by tbirdso** [comment]
Most recent [CDash run](https://open.cdash.org/viewBuildError.php?buildid=7084124) fails to include module library:
> /usr/bin/ld: cannot find -lMesh3DProcrustesAlignFilter

**Comment by tbirdso** [comment]
@thewtex This issue is similar to [Issue 2](https://github.com/InsightSoftwareConsortium/ITKOptimizationMonitor/issues/2) in the [ITKOptimizationMonitor](https://github.com/InsightSoftwareConsortium/ITKOptimizationMonitor) external module, which was resolved last week but root cause was not definitively found. Any thoughts on the best way to investigate?

**Comment by thewtex** [comment]
@tbirdso added inline comment identifying the issue in #1

**Comment by tbirdso** [comment]
Thanks @thewtex. Following removal of the `CMakeLists.txt` line I am now seeing errors linking ITK libraries:
> 2>LINK : fatal error LNK1181: cannot open input file 'ITKCommon.lib'
2>Done building project "Mesh3DProcrustesAlignFilterHeaderTest1.vcxproj" -- FAILED.
3>------ Build started: Project: Mesh3DProcrustesAlignFilterTestDriver, Configuration: Release x64 ------
3>LINK : fatal error LNK1181: cannot open input file 'ITKMetaIO.lib'
3>Done building project "Mesh3DProcrustesAlignFilterTestDriver.vcxproj" -- FAILED.

I have confirmed that `ITKCommon-5.2.lib` and `ITKMetaIO-5.2.lib` exist at `C:\repos\ITK-builds\lib\Release` and I am building the project in `Release` configuration.

**Comment by tbirdso** [comment]
Resolved in two steps:
- Remove `CMakeLists.txt` line directing project to look for `.lib` files (which are not expected in a header-only module)
- Rebuild against a full, clean build of ITK
