### ISSUE TITLE
Add to ITK as a Remote Module

### ISSUE THREAD

**Issue by tbirdso** [slicersalt/ITKShape#22]
Steps:
- Change `Mesh3DProcrustesAlignFilter` to `ITKShape` everywhere in the ITKShape repo (this was changed shortly after the project was created)
- Add remote model CMake file to ITK

See related PR: [https://github.com/InsightSoftwareConsortium/ITK/pull/2642](https://github.com/InsightSoftwareConsortium/ITK/pull/2642)

**Comment by dzenanz** [comment]
Changing a filter name to match the module name is not necessary.

**Comment by tbirdso** [comment]
The module was initially named `Mesh3DProcrustesAlignFilter` and contained the implementation for the `MeshProcrustesAlignFilter` class. We want to change the name of the module everywhere because it is confusing to have a module with the `Filter` suffix 😃
