### ISSUE TITLE
Wrapped Class Import Failure

### ISSUE THREAD

**Issue by tbirdso** [slicersalt/ITKShape#5]
## Summary
The wrapped `itk.Mesh3DProcrustesAlignFilter` cannot be instantiated in a Python workspace.

## Description
After successfully building the Python wrapping a CTest script is employed to test instantiation of the `itk.Mesh3DProcrustesAlignFilter` class. `Mesh3DProcrustesFilter` is available as an ITK module per the following output:
> Python 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import itk
\>\>\> itk.Mesh3DProcrustesAlignFilter
<module 'Mesh3DProcrustesAlignFilter'>
\>\>\> dir(itk.Mesh3DProcrustesAlignFilter)
['Mesh3DProcrustesAlignFilter', '_LazyITKModule__belong_lazy_attributes', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'itk_base_global_lazy_attributes', 'loaded_lazy_modules', 'mesh3_d_procrustes_align_filter']

However, attempts to get types or instantiate a filter object fail:
> \>\>\> itk.Mesh3DProcrustesAlignFilter.GetTypes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\repos\ITK-build\Wrapping\Generators\Python\itk\support\itkLazy.py", line 71, in __getattribute__
    value = types.ModuleType.__getattribute__(self, attr)
AttributeError: module 'Mesh3DProcrustesAlignFilter' has no attribute 'GetTypes'

> \>\>\> itk.Mesh3DProcrustesAlignFilter.New()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\repos\ITK-build\Wrapping\Generators\Python\itk\support\itkLazy.py", line 71, in __getattribute__
    value = types.ModuleType.__getattribute__(self, attr)
AttributeError: module 'Mesh3DProcrustesAlignFilter' has no attribute 'New'

## Expected behavior
`Mesh3DProcrustesAlignFilter` can be instantiated according to wrapped types

## Observed behavior
`Mesh3DProcrustesAlignFilter` is available as a Python module but cannot be referenced as a wrapped filter object

**Comment by tbirdso** [comment]
@thewtex Could you add insight on this? I recall seeing this issue before but can't remember how it was resolved.

Is it possible that the filter is not being wrapped even though the external module sharing its name is wrapped?

**Comment by tbirdso** [comment]
Further investigation into the generated `ITK-build/Wrapping/Generators/Python/itk/itkMesh3DProcrustesAlignFilter.py` indicates that template wrappings are indeed being generated:

> def itkMesh3DProcrustesAlignFilterMD3MD3_New():
    return itkMesh3DProcrustesAlignFilterMD3MD3.New()
   ...

> \# Register itkMesh3DProcrustesAlignFilterMD3MD3 in \_itkMesh3DProcrustesAlignFilterPython:
\_itkMesh3DProcrustesAlignFilterPython.itkMesh3DProcrustesAlignFilterMD3MD3_swigregister(itkMesh3DProcrustesAlignFilterMD3MD3)
itkMesh3DProcrustesAlignFilterMD3MD3___New_orig__ = \_itkMesh3DProcrustesAlignFilterPython.itkMesh3DProcrustesAlignFilterMD3MD3___New_orig__
itkMesh3DProcrustesAlignFilterMD3MD3_cast = \_itkMesh3DProcrustesAlignFilterPython.itkMesh3DProcrustesAlignFilterMD3MD3_cast

> def itkMesh3DProcrustesAlignFilterMF3MF3_New():
    return itkMesh3DProcrustesAlignFilterMF3MF3.New()
   ...

It seems like this may be a local configuration issue, but `WrapITK.pth` in `site-modules` points to the correct path:
> \# Python pth file to add itk package path to sys.path
\# for itk version "5.2.0"
C:/repos/ITK-build/Wrapping/Generators/Python

[CI checks are all passing](https://github.com/tbirdso/ITKMesh3DProcrustesAlignFilter/runs/2088982054), but logs indicate that the Python wrapping test is not being included in CTest runs:
> Start 1: Mesh3DProcrustesAlignFilterKWStyleTest
> Start 2: Mesh3DProcrustesAlignFilterInDoxygenGroup
 1/3 Test #1: Mesh3DProcrustesAlignFilterKWStyleTest ......   Passed    0.01 sec
    Start 3: itkMesh3DProcrustesAlignFilterTest
2/3 Test #2: Mesh3DProcrustesAlignFilterInDoxygenGroup ...   Passed    0.03 sec
3/3 Test #3: itkMesh3DProcrustesAlignFilterTest ..........   Passed    0.03 sec

**Comment by tbirdso** [comment]
After correcting CMake Python variables to point to my virtual environment I noticed a relevant output line:
> 15\>itkMesh3DProcrustesAlignFilter: warning(4): ITK type not wrapped, or currently not known: itk::AffineTransform< float, 3 >

I'm still seeing this error after removing `float` from the wrapping types. But, progress!

**Comment by tbirdso** [comment]
Further testing finally revealed the root issue -- _there is a naming collision between the module and the filter it contains. Changing all filter class references from `Mesh3DProcrustesAlignFilter` to `MeshProcrustesAlignFilter` generates both a) the `Mesh3DProcrustesAlignFilter` Python module and b) the `itk.MeshProcrustesAlignFilter` Python template.

I do not have permissions to change the repo name so I will submit a PR proposing the filter template class be renamed to `MeshProcrustesAlignFilter`. @thewtex is this renaming acceptable or would you prefer to rename the module so that the filter exactly matches its origins in SPHARM-PDM?

**Comment by thewtex** [comment]
@tbirdso that naming is great, thanks!

Yes, the name of a module cannot be the same as a filter it contains.

We can likely make this filter work for 2D, correct? I will create an issue.

I am thinking we should rename the repository / module name to *ITKSALT* so we can bring in other shape analysis filters. @bpaniagua does that sound good to you?
